# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestTestsuite1():
    def setup_method(self, method):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_test1(self):
        self.driver.get("https://ceshiren.com/")
        time.sleep(2)
        self.driver.set_window_size(1823, 797)
        time.sleep(2)
        # self.driver.find_element(By.LINK_TEXT, "热门").click()
        time.sleep(2)
        # self.driver.find_element(By.LINK_TEXT, "近期（5）").click()
        self.driver.close()
